version: "3.9"

services:
  simulator:
    build: .
    container_name: simulator-exam
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped